flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flaskblog/main/routes.py
from flask import Blueprint, request, render_template
from flaskblog.models import Post

main = Blueprint('main', __name__)

# home route, also root
@main.route("/")
@main.route("/home")
# function called home
def home():
    page = request.args.get('page', 1, type=int)
    # query db for all posts
    posts = Post.query.order_by(Post.date_posted.desc())\
                        .paginate(page=page, per_page=5)
    # render template for home.html, passing posts variable to display on home page
    return render_template("home.html", posts=posts)


# about route
@main.route("/about")
def about():
    return render_template("about.html")

flaskblog/posts/routes.py
from flask import (Blueprint, flash, redirect, url_for,
                   render_template, abort, request)
from flask_login import login_required, current_user
from flaskblog import db
from flaskblog.posts.forms import PostForm
from flaskblog.models import Post

posts = Blueprint('posts', __name__)


# new post route, also accepts POST
@posts.route("/post/new", methods=['GET', 'POST'])
# required login decorator
@login_required
def new_post():
    # create that form
    form = PostForm()
    # did they submit a valid form?
    if form.validate_on_submit():
        # create a Post
        post = Post(title=form.title.data,
                    content=form.content.data,
                    author=current_user)
        # add to db
        db.session.add(post)
        db.session.commit()
        # show message
        flash('Your post has been created!', 'success')
        # send them home after logging in
        return redirect(url_for('main.home'))
    # for GET request, just base create post template
    return render_template('create_post.html', title='New Post',
                           form=form, legend="New Post")


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=["GET", "POST"])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash("Your post has been updated", 'succes')
        return redirect(url_for('post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post',
                           form=form, legend="Update Post")


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import Blueprint, redirect, url_for, render_template, flash, request
from flaskblog import bcrypt, db
from flaskblog.users.forms import (RegistrationForm, RequestResetForm,
                                   ResetPasswordForm, LoginForm,
                                   UpdateAccountForm)
from flask_login import current_user, login_user, logout_user, login_required
from flaskblog.models import User, Post
from flaskblog.users.utils import send_reset_email, save_picture

users = Blueprint('users', __name__)


# register route, also accepts POST
@users.route("/register", methods=['GET', 'POST'])
def register():
    # is user logged in? <- this probably actually means if they're registration is successful?
    # how do they get to login if they are already logged in, maybe they typed in the URL
    if current_user.is_authenticated:
        # send them to the home page, they dont need to login
        return redirect(url_for('main.home'))
    # isntantiate the form
    form = RegistrationForm()
    # did they validly submit a form?
    if form.validate_on_submit():
        # lets hash that password
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        # get the username from the data
        username = form.username.data
        # create a User model instance
        user = User(username=username,
                    email=form.email.data,
                    password=hashed_password)
        # add user to db
        db.session.add(user)
        db.session.commit()
        # show message
        flash(f'Account created for {username}!, you can now log in!',
              'success')
        # using that redirect->url and it receives the function name for the login route
        return redirect(url_for('users.login'))
    # if its just GET request, show them the registration form
    return render_template('register.html', title='Register', form=form)


# login route, also accepts POST
@users.route("/login", methods=["GET", 'POST'])
def login():
    # if they are already loggged in
    if current_user.is_authenticated:
        # send them home, notice redirect and 'home' is function name
        return redirect(url_for('main.home'))
    # login form created
    form = LoginForm()
    # did they submit the form?
    if form.validate_on_submit():
        # search db for email they put in
        user = User.query.filter_by(email=form.email.data).first()
        # if user exists, and the password matches our saved one
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            # user session management to log in user, check if they want to be rememebered
            login_user(user, remember=form.remember.data)
            # look for the page they were trying ot get to that redirected them here
            next_page = request.args.get('next')
            if next_page:
                return redirect(next_page)
            else:
                return redirect(url_for('main.home'))
        # login fails
        else:
            # tell them and stay on the page
            flash('Login Unsuccessful. Please check username and password',
                  'danger')
    # GET request just returns the base page
    return render_template('login.html', title='Register', form=form)


# logout route
@users.route("/logout")
def logout():
    # session handler to logout
    logout_user()
    # send them home
    return redirect(url_for('main.home'))


# account route, also accepts POST
@users.route("/account", methods=['GET', 'POST'])
# login required decorator
@login_required
def account():
    # option to update account
    form = UpdateAccountForm()
    # did they submit and correctly?
    if form.validate_on_submit():
        # is there a picture
        if form.picture.data:
            # handle it.
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        # update username and email
        current_user.username = form.username.data
        current_user.email = form.email.data
        # commit to db
        db.session.commit()
        # show message
        flash('Your account has been updated!',
              'success')
        # send back to account page (to display the changes prolly we need to reload)
        return redirect(url_for('users.account'))
    # oh is it a get request?
    elif request.method == 'GET':
        # gotta show their current username and email
        form.username.data = current_user.username
        form.email.data = current_user.email
    # load their profile pic, url_for can be used not just getting routes?
    # url_for probbably just generates the url, the redirect sends us there.
    # interesting that we do a function something and now a filepath to a file
    image_file = url_for('static',
                         filename='profile_pics/' + current_user.image_file)
    # then render the account page with the image and the form
    return render_template('account.html',
                           title='Account',
                           image_file=image_file,
                           form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash("An email has been sent with instructions to reset your password.", 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html',
                           title='Reset Password',
                           form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data)\
                                .decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been changed! You are now able to log in.',
              'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html',
                           title='Reset Password',
                           form=form)

flaskblog/templates/about.html
{% extends "layout.html" %}
{% block content %}
        <h1>About Page</h1>
{% endblock content %}

flaskblog/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ image_file }}">
            <div class="media-body">
                <h2 class="account-heading">{{ current_user.username }}</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
        </div>
        <!-- FORM HERE -->
        <form method='POST' action="", enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flaskblog/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
    <div class='content-section'>
        <form method='POST' action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.content.label(class="form-control-label") }}
                    {% if form.content.errors %}
                        {{ form.content(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.content(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flaskblog/templates/home.html
<!-- syntax for opening python code blocks inside jinja templates -->
<!-- uses a base layout for everypage -->
{% extends "layout.html" %}
{% block content %}
    <!-- cycling through posts to display, there is an `endfor` code block -->
    {% for post in posts.items %}
        <!-- what is an html article? what are the bootstrap classes `media` and `content-section`? -->
        <article class="media content-section">
            <!-- displays the author of posts image. `url_for` is best practice for linking around the app -->
            <img class="rounded-circle articl-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
            <!-- master div holding each post -->
            <div class="media-body">
                <!-- div holding the author and date posted -->
                <div class="article-metadata">
                    <!-- double curlys is how you insert a python variable but it needs to be passed to the render_template func -->
                    <!-- `a` is a link, right now just back to the same page -->
                    <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                    <!-- don't quite know what a small is but appears to be like a small header maybe -->
                    <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                </div>
                <!-- post title, h2 is a header I know that, and the title here is a link -->
                <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                <!-- `p` is paragraph, the posts content. probably want just a teaser and the title links to the rest of it-->
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article> 
    <!-- close that for loop explicitly -->
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% endif %}

        {% else %}
            ...
        {% endif %}
    {% endfor %}
<!-- close code blocks explicitly -->
{% endblock content %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Flask Blog - {{ title }}</title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %}

</head>
<body>

    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="{{ url_for('main.home') }}"></a>Flask Blog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                        <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if current_user.is_authenticated %}
                            <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                            <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                            <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                        {% else %}
                            <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                            <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                {% block content %}{% endblock %}
            </div>
            <div class="col-md-4">
                <div class="content-section">
                    <h3>Our Sidebar</h3>
                    <p class='text-muted'>You can put any information here you'd like.
                        <ul class="list-group">
                            <li class="list-group-item list-group-item-light">Latest Posts</li>
                            <li class="list-group-item list-group-item-light">Announcements</li>
                            <li class="list-group-item list-group-item-light">Calendars</li>
                            <li class="list-group-item list-group-item-light">etc</li>
                        </ul>
                    </p>
                </div>
            </div>
        </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

flaskblog/templates/login.html
{% extends "layout.html" %}
{% block content %}
        <div class='content-section'>
            <form method='POST' action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Login</legend>
                    <div class="form-group">
                        {{ form.email.label(class="form-control-label") }}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.password.label(class="form-control-label") }}
                        {% if form.password.errors %}
                            {{ form.password(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-check">
                        {{ form.remember(class="form-check-input") }}
                        {{ form.remember.label(class="form-check-label") }}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                    <small class="text-muted ml-2">
                        <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                    </small>
                </div>
            </form>
        </div>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need an Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign Up Now!</a>
            </small>
        </div>
{% endblock content %}

flaskblog/templates/post.html
<!-- syntax for opening python code blocks inside jinja templates -->
<!-- uses a base layout for everypage -->
{% extends "layout.html" %}
{% block content %}
    <!-- what is an html article? what are the bootstrap classes `media` and `content-section`? -->
    <article class="media content-section">
        <!-- displays the author of posts image. `url_for` is best practice for linking around the app -->
        <img class="rounded-circle articl-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        <!-- master div holding each post -->
        <div class="media-body">
            <!-- div holding the author and date posted -->
            <div class="article-metadata">
                <!-- double curlys is how you insert a python variable but it needs to be passed to the render_template func -->
                <!-- `a` is a link, right now just back to the same page -->
                <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                <!-- don't quite know what a small is but appears to be like a small header maybe -->
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                {% if post.author == current_user %}
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                    </div>
                {% endif %}
            </div>
            <!-- post title, h2 is a header I know that, and the title here is a link -->
            <h2 class="article-title">{{ post.title }}</h2>
            <!-- `p` is paragraph, the posts content. probably want just a teaser and the title links to the rest of it-->
            <p class="article-content">{{ post.content }}</p>
        </div>
    </article> 
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                        <input class="btn btn-danger" type="submit" value="Delete">
                    </form>
                </div>
            </div>
        </div>
    </div>
<!-- close code blocks explicitly -->
{% endblock content %}

flaskblog/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class='content-section'>
        <form method='POST' action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flaskblog/templates/user_posts.html
<!-- syntax for opening python code blocks inside jinja templates -->
<!-- uses a base layout for everypage -->
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
    <!-- cycling through posts to display, there is an `endfor` code block -->
    {% for post in posts.items %}
        <!-- what is an html article? what are the bootstrap classes `media` and `content-section`? -->
        <article class="media content-section">
            <!-- displays the author of posts image. `url_for` is best practice for linking around the app -->
            <img class="rounded-circle articl-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
            <!-- master div holding each post -->
            <div class="media-body">
                <!-- div holding the author and date posted -->
                <div class="article-metadata">
                    <!-- double curlys is how you insert a python variable but it needs to be passed to the render_template func -->
                    <!-- `a` is a link, right now just back to the same page -->
                    <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                    <!-- don't quite know what a small is but appears to be like a small header maybe -->
                    <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                </div>
                <!-- post title, h2 is a header I know that, and the title here is a link -->
                <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                <!-- `p` is paragraph, the posts content. probably want just a teaser and the title links to the rest of it-->
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article> 
    <!-- close that for loop explicitly -->
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% endif %}

        {% else %}
            ...
        {% endif %}
    {% endfor %}
<!-- close code blocks explicitly -->
{% endblock content %}